### ISSUE TITLE
Possible Logical Error (SubtitleSeq#91)

### ISSUE THREAD

**Issue by AbdulmajeedAlOmari** [AbdulmajeedAlOmari/CSC212#1]
https://github.com/AbdulmajeedAlOmari/CSC212/blob/31eb8e0bbe576a65c6ec7d1f9e8fc915fbbe0f22/CSC212%20Project/src/SubtitleSeq.java#L91

the time interval format is [ Seconds.MS, Seconds.MS)
What if the subtitle time interval is [197.156, xxx) , where x is (don't care)
and we called the method getSubtitles( [193.260, xxx) )    //getSubtitles(Time startTime, Time endTime)

problem is in these conditions :   {{ tempSSec >= sTSec && sTime.getMS() >= startTime.getMS() }}
1)  (197 >= 193 ) TRUE
2) (156 >= 260) FALSE     --which is logically unacceptable--

Therefore, the method won't consider the previous subtitle in the List!

`
        
    List<Subtitle> subtitles = new LinkedList<>();
		
		if(subSeq.empty())
			return subtitles;
		
		subSeq.findFirst();
		
		Subtitle temp = null;
		Time sTime = null, eTime = null;
		int sTSec = startTime.getHH()*3600 + startTime.getMM()*60 + startTime.getSS();
		int eTSec =  endTime.getHH()*3600 + endTime.getMM()*60 + endTime.getSS();
		
		int tempSSec = 0;
		int tempESec = 0;
		
		while(!subSeq.last()) {
			temp = subSeq.retrieve();
			sTime = temp.getStartTime();
			eTime = temp.getEndTime();
			
			tempSSec = sTime.getHH()*3600 + sTime.getMM()*60 + sTime.getSS();
			tempESec = eTime.getHH()*3600 + eTime.getMM()*60 + eTime.getSS();
			
                        //the problem is here (first line)
			if( (tempSSec >= sTSec && sTime.getMS() >= startTime.getMS())
					|| (tempESec <= eTSec && eTime.getMS() <= endTime.getMS())
					|| (tempSSec <= sTSec && sTime.getMS() < startTime.getMS()
						&& 	tempESec >= eTSec && eTime.getMS() > endTime.getMS()))
				subtitles.insert(temp);
			
			subSeq.findNext();
`

**Comment by AbdulmajeedAlOmari** [comment]
Possible Solution : tempSSec > sTSec || ( tempSSec== sTSec && sTime.getMS() >= startTime.getMS() )

**Comment by MohammadTashkandi** [comment]
solution to end all our problems:
method to convert time to seconds.

private double toSec(Time time) {
		return time.getHH()*3600 + time.getMM()*60 + time.getSS() + (double)time.getMS()/1000;
	}

implementing methods using toSec reduces code drastically, and improves readability.

public Subtitle getSubtitle(Time time) {
		if (subSeq.empty()){
			return null;
		}else {
			subSeq.findFirst();
			double specified = toSec(time);
			while (!subSeq.last()) {
				double sTime = toSec(subSeq.retrieve().getStartTime());
				double eTime = toSec(subSeq.retrieve().getEndTime());
				if (specified >= sTime && specified < eTime) {
					return subSeq.retrieve();
				}
				subSeq.findNext();
			}
			double sTime = toSec(subSeq.retrieve().getStartTime());
			double eTime = toSec(subSeq.retrieve().getEndTime());
			if (specified >= sTime && specified < eTime) {
				return subSeq.retrieve();
			}else {
				return null;
			}
		}
	}

public List<Subtitle> getSubtitles(Time startTime, Time endTime) {
		List<Subtitle> subtitles = new LinkedList<>();
		if (subSeq.empty()) {
			return subtitles;
		}else {
			double specifiedStart = toSec(startTime);
			double specifiedEnd = toSec(endTime);
			subSeq.findFirst();
			while (!subSeq.last()) {
				double sTime = toSec(subSeq.retrieve().getStartTime());
				double eTime = toSec(subSeq.retrieve().getEndTime());
				
				if(sTime >= specifiedStart || eTime <= specifiedEnd || (sTime<specifiedStart && eTime>specifiedEnd)){
					subtitles.insert(subSeq.retrieve());
				}
			}
			double sTime = toSec(subSeq.retrieve().getStartTime());
			double eTime = toSec(subSeq.retrieve().getEndTime());
			
			if(sTime >= specifiedStart || eTime <= specifiedEnd || (sTime<specifiedStart && eTime>specifiedEnd)){
				subtitles.insert(subSeq.retrieve());
			}
		}
		return subtitles;
	}

**Comment by AbdulmajeedAlOmari** [comment]
Perfect solution 👍 but we need to make sure about using (double) in the
boolean expression.
